### ISSUE TITLE
dockerise

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/mapp#10]
Mapp should be dockerised.

Key features needed:

- production flask server
- redis server (stored appropriately)
- tools script runnable

Help here is appreciated.

**Comment by elenalape** [comment]
why should it be dockerised?

**Comment by qaisjp** [comment]
Done in https://github.com/compsoc-edinburgh/mapp-site/commit/15ee8995d768b623650602014b6252391ae7b5a5#diff-3254677a7917c6c01f55212f86c57fbf
