### ISSUE TITLE
Cascaders Online

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/mapp#15]
@ggilligan12 and I were discussing Cascaders. He came up with the idea of adding it to mapp.

Plan of action:
- a button to make yourself appear on the map for everyone
    - a checkbox to display or hide your name
- a freeform text box to describe what exactly you are happy to help with
- the button should be toggleable, so you can temporarily disable "cascader mode" without losing the freeform text (basically a DnD for cascading, as you may still want your friends to see you)
- a way to ban users who abuse the freeform text box

**Comment by qaisjp** [comment]
# What is Cascaders?

Cascaders is a peer-support programme that started off many many years ago. There used to be a box of teddies left outside the ITO, and if you were happy lending someone a hand you could just take a teddy and prop it on top of your lab machine.

Hopefully these teddies will make a comeback, but for now, why not _cascade_ through mapp?

# How does it work?

Enter a tagline explaining what you're happy to help out with (please don't be rude!) and choose whether you'd like your name to appear. Then, when you're at a DICE machine, you'll show up on the map!

Example taglines:
- "Anything!"
- "Machine Learning"
- "inf1/2 courses"
- "Python"

**Comment by Visgean** [comment]
Awesome idea
