### ISSUE TITLE
Find Friends directly

### ISSUE THREAD

**Issue by AlexJLP** [compsoc-edinburgh/mapp#2]
The friend system currently displays friends with a separate symbol on the map. If I want to find a specific friend, I have to go through all different rooms they are likely to be in and observe the icons. It'd be better if there was a `find friend(s)` feature, showing me the location of a friend directly - given they are logged in (and consented to this?).

**Comment by qaisjp** [comment]
done in https://github.com/compsoc-edinburgh/mapp-site/commit/fdd47f058935adb0e2f4911dfa0bfcc343b727d1

desperately need to add friend confirmations
