### ISSUE TITLE
Consider alternatives to loginctl for graphical session owner

### ISSUE THREAD

**Issue by sleepyfoxen** [compsoc-edinburgh/mapp#25]
Currently, we use `loginctl` ([man page](http://man7.org/linux/man-pages/man1/loginctl.1.html)) to see who's logged in.

An alternative solution would be to check for a process that is launched along with a graphical session, such as those relating to `dbus`:

```bash
ps -ef |
    grep -e 'dbus-launch.*--exit-with-session' |
    fgrep -v -e grep |
    awk '{print $1}'
```

Another option is to find which processes are children of the display manager, `lightdm`. (You can find the display manager by checking who spawned X, but on DICE it'll always be lightdm). The window manager should be a child, so checking the owner of the child processes will give you who has a graphical session.

```bash
ps -ho user --ppid $(pidof lightdm) |
    fgrep -v -e 'root'
```

I think the second option would be a lot neater and more reliable. Thoughts?

**Comment by qaisjp** [comment]
imo 86fccb4 still works in a lot of cases (and works better than without 86fccb4) so i think we should keep it around until we can think of a full fix.

**Comment by qaisjp** [comment]
Refers to these commits in this repo: 86fccb4, a026646, b4ce36c
