### ISSUE TITLE
Remove Cascaders feature?

### ISSUE THREAD

**Issue by qaisjp** [compsoc-edinburgh/mapp#29]
cc-ing various people @sleepyfoxen @Visgean @neanias 

I think I should remove this feature. I don't think it really works well in its current form. The people that most often need help probably don't know that mapp exists, and not a lot of people use it anyway.

I've personally never been approached! And I don't know of anyone being approached after the "hype" of the initial release.

It was cool to make but in the end I think it is an example of feature bloat.

**Comment by timmygill** [comment]
i agree it hasn't really taken off in its current form.

**Comment by neanias** [comment]
Not sure where the cascaders feature even is. Can you point me in its direction, please?

**Comment by qaisjp** [comment]
all backend logic is in https://github.com/compsoc-edinburgh/mapp/blob/master/website/map/views.py with frontend stuff in https://github.com/compsoc-edinburgh/mapp/blob/master/website/map/static/js/mapp.js

**Comment by himmelmaus** [comment]
I got approached once by someone needing help with matplotlib

**Comment by qaisjp** [comment]
nice, when was that @findoslice ?
